# Generated by Django 6.0.3 on 2026-03-21 04:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('favorite_character', models.CharField(blank=True, choices=[('Goku (Dragon Ball)', 'Goku'), ('Naruto (Naruto)', 'Naruto'), ('Sasuke (Naruto)', 'Sasuke'), ('Sakura (Naruto)', 'Sakura'), ('Luffy (One Piece)', 'Luffy'), ('Zoro (One Piece)', 'Zoro'), ('Sanji (One Piece)', 'Sanji'), ('Nami (One Piece)', 'Nami'), ('Usopp (One Piece)', 'Usopp'), ('Chopper (One Piece)', 'Chopper'), ('Robin (One Piece)', 'Robin'), ('Franky (One Piece)', 'Franky'), ('Brook (One Piece)', 'Brook'), ('Shanks (One Piece)', 'Shanks'), ('Kaido (One Piece)', 'Kaido'), ('Big Mom (One Piece)', 'Big Mom'), ('Blackbeard (One Piece)', 'Blackbeard'), ('Akainu (One Piece)', 'Akainu'), ('Aokiji (One Piece)', 'Aokiji'), ('Kizaru (One Piece)', 'Kizaru'), ('Ace (One Piece)', 'Ace'), ('Sabo (One Piece)', 'Sabo'), ('Boa Hancock (One Piece)', 'Boa Hancock'), ('Law (One Piece)', 'Law'), ('Saitama (One Punch Man)', 'Saitama'), ('Deku (My Hero Academia)', 'Deku'), ('Tanjiro (Demon Slayer)', 'Tanjiro'), ('Eren (Attack on Titan)', 'Eren'), ('Mikasa (Attack on Titan)', 'Mikasa'), ('Levi (Attack on Titan)', 'Levi'), ("Jotaro (JoJo's Bizarre Adventure)", 'Jotaro'), ("Dio (JoJo's Bizarre Adventure)", 'Dio'), ('Edward (Fullmetal Alchemist)', 'Edward'), ('Alphonse (Fullmetal Alchemist)', 'Alphonse'), ('Gon (Hunter x Hunter)', 'Gon'), ('Killua (Hunter x Hunter)', 'Killua'), ('Hisoka (Hunter x Hunter)', 'Hisoka'), ('Gojo (Jujutsu Kaisen)', 'Gojo'), ('Itadori (Jujutsu Kaisen)', 'Itadori'), ('Megumi (Jujutsu Kaisen)', 'Megumi'), ('Nobara (Jujutsu Kaisen)', 'Nobara'), ('Sukuna (Jujutsu Kaisen)', 'Sukuna'), ('Ichigo (Bleach)', 'Ichigo'), ('Rukia (Bleach)', 'Rukia'), ('Aizen (Bleach)', 'Aizen'), ('Saiki (The Disastrous Life of Saiki K.)', 'Saiki'), ('Senku (Dr. Stone)', 'Senku'), ('Kohaku (Dr. Stone)', 'Kohaku'), ('Yusuke (Yu Yu Hakusho)', 'Yusuke'), ('Hiei (Yu Yu Hakusho)', 'Hiei'), ('Kurama (Yu Yu Hakusho)', 'Kurama'), ('Kenshin (Rurouni Kenshin)', 'Kenshin'), ('Inuyasha (Inuyasha)', 'Inuyasha'), ('Sesshomaru (Inuyasha)', 'Sesshomaru'), ('Vash (Trigun)', 'Vash'), ('Spike (Cowboy Bebop)', 'Spike'), ('L (Death Note)', 'L'), ('Light (Death Note)', 'Light'), ('Ryuk (Death Note)', 'Ryuk'), ('Guts (Berserk)', 'Guts'), ('Griffith (Berserk)', 'Griffith'), ('Alucard (Hellsing)', 'Alucard'), ('Ken (Tokyo Revengers)', 'Ken'), ('Mikey (Tokyo Revengers)', 'Mikey'), ('Draken (Tokyo Revengers)', 'Draken'), ('Toge (Jujutsu Kaisen)', 'Toge'), ('Maki (Jujutsu Kaisen)', 'Maki'), ('Panda (Jujutsu Kaisen)', 'Panda'), ('Hinata (Haikyuu!!)', 'Hinata'), ('Kageyama (Haikyuu!!)', 'Kageyama'), ('Nishinoya (Haikyuu!!)', 'Nishinoya'), ('Sawamura (Haikyuu!!)', 'Sawamura')], help_text='Seu personagem de anime favorito', max_length=80)),
                ('collection_theme', models.CharField(blank=True, choices=[('shonen', 'Shonen'), ('isekai', 'Isekai'), ('mecha', 'Mecha'), ('slice_of_life', 'Slice of Life'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('action', 'Action'), ('adventure', 'Adventure')], help_text='Tema visual da sua coleção baseado no gênero de anime que você mais gosta', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=350)),
                ('profile_picture', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
