# Generated by Django 6.0.3 on 2026-03-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collection_theme',
            field=models.CharField(blank=True, choices=[('portal', 'Portal Gun'), ('pickle', 'Pickle Rick'), ('citadel', 'Citadel of Ricks'), ('c137', 'Dimension C-137'), ('purge', 'Purge Planet'), ('meeseeks', 'Mr. Meeseeks Box'), ('unity', 'Unity Hive Mind'), ('morty', 'Morty Adventure')], help_text='tema visual da sua coleção', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_character',
            field=models.CharField(blank=True, choices=[('Rick Sanchez', 'Rick Sanchez'), ('Morty Smith', 'Morty Smith'), ('Summer Smith', 'Summer Smith'), ('Beth Smith', 'Beth Smith'), ('Jerry Smith', 'Jerry Smith'), ('Mr. Poopybutthole', 'Mr. Poopybutthole'), ('Birdperson', 'Birdperson'), ('Squanchy', 'Squanchy'), ('Evil Morty', 'Evil Morty'), ('Unity', 'Unity'), ('Mr. Meeseeks', 'Mr. Meeseeks'), ('Krombopulos Michael', 'Krombopulos Michael'), ('Abradolf Lincler', 'Abradolf Lincler'), ('Scary Terry', 'Scary Terry'), ('Zeep Xanflorp', 'Zeep Xanflorp')], help_text='Seu personagem de anime favorito de rick and morty', max_length=80),
        ),
    ]
